[package]
name = "linkcheck"
version = "0.1.0"
authors = ["ftilde <ftilde@protonmail.com>"]

[profile.release]
debug = true

[dependencies]
structopt = "0.2.1"
goblin = "0.0.15"
cpp_demangle = "0.2.9"
itertools = "0.7.8"
groupable = "0.2"
term = "0.5"
glob = "0.2.11"
